import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { primaryColor } from "./style.css"

import { dark, neobrutalism, shadesOfPurple } from '@clerk/themes';


const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// export default function RootLayout({
//     children,
// }: {
//     children: React.ReactNode;
// }) {
//     return (
//         <ClerkProvider>
//             <html lang="en">
//                 <body className={inter.className}>{children}</body>
//             </html>
//            </ClerkProvider>
//     );
// }

// export default function RootLayout({
//     children,
//   }: {
//     children: React.ReactNode
//   }) {
//     return (
//     //   <ClerkProvider
//     //     appearance={{
//     //     variables: { colorPrimary: "orange" },
//     //       signIn: { 
//     //       variables: {
//     //             colorPrimary: "red",
//     //         //   colorText: "orange"
//     //         } 
//     //       },
//     //     }}

//      // >
//         <SignIn
//             appearance={{
//                 elements: {
//                     formButtonPrimary:
//                         "bg-slate-500 hover:bg-slate-400 text-sm normal-case",
//                 },
//             }}
//             />
//         <html lang="en">
//           <body>{children}</body>
//         </html>
//       </ClerkProvider>
//     )
//   }


export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider
            appearance={{
                variables: {
                    colorPrimary: "blue",
                    colorText: "black"
                }
            }}
        >
            <html lang="en">
                <body>{children}</body>
            </html>
        </ClerkProvider>
    )
}
